#ifndef STKQ_POLICY_H
#define STKQ_POLICY_H

namespace stkq {
    enum TYPE {
        INDEX_HNSW, INIT_RANDOM, INDEX_DEG, INDEX_WTNG,

        INIT_HNSW, INIT_DEG, INIT_WTNG,

        SEARCH_ENTRY_RAND, SEARCH_ENTRY_CENTROID, SEARCH_ENTRY_SUB_CENTROID, SEARCH_ENTRY_NONE, 

        L_SEARCH_ASCEND, L_SEARCH_SET_RECALL, L_SEARCH_ASSIGN,

        ROUTER_GREEDY, ROUTER_HNSW, DUAL_ROUTER_HNSW, ROUTER_DEG, ROUTER_WTNG
    };
}

#endif 